[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "meteoplots"
version = "0.1.0"
description = "Funções para plotagem meteorológica"
authors = [{ name = "Jose Flores" }]
dependencies = []
